from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
EXPORT_DIR = DATA_DIR / "exports"
DEFAULT_TEAM = "전북"
DEFAULT_TARGET_SCORE = 87.0
MAPPING_FILE = PROJECT_ROOT / "팀소속_대리점명_매장명_매칭.xlsx"
EXPORT_TOP_N_STORES = 64
EXPORT_TOP_N_TYPES = 30
EXPORT_TOP_N_AUDIT = 100
MAPPING_UNMATCHED_WARN_RATE = 0.05
